# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.GenericIPAddressField(verbose_name='TITLE')),
                ('number', models.IntegerField(max_length=4, verbose_name='NUMBER')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('date', models.CharField(max_length=10, verbose_name='DATE')),
                ('time', models.CharField(max_length=10, verbose_name='TIME')),
                ('text', models.TextField(verbose_name='TEXT')),
                ('html', models.CharField(max_length=30, verbose_name='HTML')),
            ],
        ),
    ]
